name: Deploy to Hugging Face

on:
  push:
    paths:
      - 'hf/**'
      - '.github/workflows/hf-sync.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "yashineonline@gmail.com"
          git config --global user.name "yashineonline"

      - name: Install dependencies
        run: pip install huggingface_hub

      - name: Push hf/ to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd hf
          git init
          git branch -m main  # Rename branch from 'master' to 'main'
          git remote add origin https://yashineonline:${HF_TOKEN}@huggingface.co/spaces/yashineonline/legal-hf
          git add .
          git commit -m "Auto update from GitHub Actions"
          git push --force origin main
